<a href="https://colab.research.google.com/github/pat-ch0/NumPy-intro/blob/main/Exercices_1_1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction à NumPy

Ce cours présente la bibliothèque NumPy, un outil essentiel pour le calcul scientifique en Python. NumPy fournit des structures de données puissantes, telles que les tableaux multidimensionnels, ainsi que des fonctions mathématiques optimisées pour travailler avec ces tableaux.

NumPy est largement utilisé en science des données, en apprentissage automatique et dans de nombreux autres domaines scientifiques pour effectuer des calculs numériques complexes de manière efficace.

Tester les commandes suivantes

`import numpy as np`

In [1]:
import numpy as np

`as` crée un alias ou un raccourci pour la bibliothèque `numpy`. Au lieu d'écrire `numpy` chaque fois que vous souhaitez utiliser l'une de ses fonctions ou de ses objets, vous pouvez simplement utiliser `np`. Il s'agit d'une convention dans la communauté Python pour l'utilisation de NumPy.

`mylist = [1,2,3]`

In [2]:
mylist = [1,2,3]

`type(mylist)`

In [3]:
type(mylist)

list

`np.array(mylist)`

In [4]:
np.array(mylist)

array([1, 2, 3])

`mylist`

In [9]:
mylist

[1, 2, 3]

`myarr = np.array(mylist)`

In [7]:
myarr = np.array(mylist)

`myarr`

In [8]:
myarr

array([1, 2, 3])

`type(myarr)`

In [10]:
type(myarr)

numpy.ndarray

`my_matrix = [[1,2,3],[4,5,6],[7,8,9]]`

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

`np.array(my_matrix)`

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`np.arange(0,10)`


In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`np.arange(0,10,2)`

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

`np.arange(0,101,2)`

In [15]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

`np.arange(0,101,20)`

In [16]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])


```
import numpy as np

# Création d'un tableau à partir d'une liste
mylist = [1, 2, 3]
myarr = np.array(mylist)
print(myarr)

# Création d'un tableau de zéros
zeros_arr = np.zeros(5)
print(zeros_arr)

# Création d'un tableau avec une séquence de nombres
seq_arr = np.arange(0, 10, 2)
print(seq_arr)

# Accès aux attributs d'un tableau
print(seq_arr.shape)
print(seq_arr.dtype)
```



In [17]:
import numpy as np

# Création d'un tableau à partir d'une liste
mylist = [1, 2, 3]
myarr = np.array(mylist)
print(myarr)

# Création d'un tableau de zéros
zeros_arr = np.zeros(5)
print(zeros_arr)

# Création d'un tableau avec une séquence de nombres
seq_arr = np.arange(0, 10, 2)
print(seq_arr)

# Accès aux attributs d'un tableau
print(seq_arr.shape)
print(seq_arr.dtype)

[1 2 3]
[0. 0. 0. 0. 0.]
[0 2 4 6 8]
(5,)
int64




```
arr = np.arange(0, 11)

# Accès au 8ème élément
print(arr[8])

# Sélection des éléments de l'index 1 à 4
print(arr[1:5])

# Indexation booléenne
bool_arr = arr > 4
print(arr[bool_arr])
```



In [19]:
arr = np.arange(0, 11)

# Accès au 8ème élément
print(arr[8])

# Sélection des éléments de l'index 1 à 4
print(arr[1:5])

# Indexation booléenne
bool_arr = arr > 4
#print(bool_arr)
print(arr[bool_arr])

8
[1 2 3 4]
[False False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]




```
arr = np.arange(0, 10)

# Addition de 5 à chaque élément
print(arr + 5)

# Calcul de la racine carrée de chaque élément
print(np.sqrt(arr))

# Calcul de la somme de tous les éléments
print(arr.sum())
```



In [20]:
arr = np.arange(0, 10)

# Addition de 5 à chaque élément
print(arr + 5)

# Calcul de la racine carrée de chaque élément
print(np.sqrt(arr))

# Calcul de la somme de tous les éléments
print(arr.sum())

[ 5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
45




---





```
np.zeros(5)
```



Ce code utilise la bibliothèque NumPy (np) pour créer un nouveau tableau.

Examinons les composants :

``` np```  : fait référence à la bibliothèque NumPy, qui a été importée à l'aide de import numpy as np. NumPy fournit des outils puissants pour travailler avec des données numériques en Python, y compris les tableaux.

``` zeros()```  : une fonction de NumPy qui crée un tableau rempli de zéros.

``` (5)```  : l'argument passé à la fonction zeros(). Il spécifie la forme du tableau que vous souhaitez créer. Dans ce cas, il s'agit d'un nombre unique, 5, indiquant que vous souhaitez un tableau unidimensionnel de 5 éléments.

En substance, cette ligne de code crée un tableau NumPy unidimensionnel contenant 5 éléments, tous initialisés à 0.

Imaginez que vous créez un conteneur avec 5 emplacements, et que chaque emplacement est initialement rempli avec la valeur 0. Ce tableau peut ensuite être utilisé pour stocker et manipuler des données numériques dans vos programmes Python.

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])



---





```
np.zeros((5,5))
```

Cette ligne de code crée un tableau à deux dimensions (aussi appelé matrice) rempli de zéros.



``` ((5, 5))```  : l'argument passé à la fonction ``` zeros()``` . Il spécifie la forme ou les dimensions du tableau que vous souhaitez créer. Dans ce cas, (5, 5) représente un tableau à deux dimensions avec 5 lignes et 5 colonnes.

In [22]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])



---





```
np.zeros((2,5))
```



In [23]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])



```
np.ones((4,4))
```



In [24]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])



```
np.ones(5)
```



In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])



---





```
np.linspace(0,10,3)
```

Cette ligne de code utilise la fonction `np.linspace()` pour créer un tableau de nombres uniformément espacés sur un intervalle spécifié.

`linspace()` : fonction de NumPy qui génère une séquence de nombres uniformément espacés.
`0` : valeur de début de la séquence.
`10` : valeur de fin de la séquence.
`3` : nombre total d'éléments que vous souhaitez dans la séquence.

Imaginez que vous voulez diviser la plage de 0 à 10 en 3 parties égales. `np.linspace(0, 10, 3)` vous donnerait les valeurs qui marquent ces divisions : `[0., 5., 10.]`. La fonction garantit que les nombres du tableau sont espacés uniformément entre les points de début et de fin.

`linspace()` inclut les valeurs de début et de fin dans le tableau de sortie.
Elle est particulièrement utile pour créer des séquences numériques pour le traçage de graphiques, les simulations ou d'autres calculs numériques où vous avez besoin d'un nombre spécifique de points uniformément espacés dans une plage donnée.

In [26]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

---



```
np.linspace(0,10,11)
```



In [27]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])



```
np.linspace(0,10,10)
```



In [28]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])



```
np.linspace(0,5,21)
```



In [29]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])



```
len(np.linspace(0,5,21))
```



In [30]:
len(np.linspace(0,5,21))

21



```
np.eye(5)
```



In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])



```
np.random.rand(1)
```



In [34]:
np.random.rand(1)

array([0.20579068])



```
np.random.rand(1)
```



In [35]:
np.random.rand(1)

array([0.07045321])



```
np.random.rand(5,6)
```



In [40]:
np.random.rand(5,6)

array([[0.11080862, 0.87913543, 0.85627608, 0.4665087 , 0.39771933,
        0.27563359],
       [0.01682312, 0.73476471, 0.54883519, 0.94311133, 0.84389405,
        0.98427261],
       [0.03675625, 0.09153325, 0.37076584, 0.88471562, 0.55668477,
        0.91666772],
       [0.14444196, 0.04625405, 0.66727287, 0.37480184, 0.26882254,
        0.44298036],
       [0.58449697, 0.48532109, 0.65065024, 0.27126039, 0.28503872,
        0.95012687]])



```
np.random.randn(10)
```



In [44]:
np.random.randn(10)

array([-1.43878927, -0.43160387,  1.1713463 , -2.76877987, -0.64097737,
       -1.54987175,  0.29973823,  0.31392518,  0.29894874, -1.50600774])

In [45]:
np.random.randn(2,3)

array([[-0.14160342,  1.7220267 , -0.07921077],
       [-0.42081827,  0.08761271,  1.6385407 ]])



```
np.random.randint(0,101,5)
```



In [47]:
np.random.randint(0,101,5)

array([36,  1, 73, 11, 22])



```
np.random.randint(0,101,(4,5))
```



In [50]:
np.random.randint(0,101,(4,5))

array([[  1,   8,   5,  13,  77],
       [ 88,  77, 100,  46,  22],
       [ 62,  27,  20,  23,   9],
       [ 27,  48,  33,  12,  25]])



```
np.random.randint(0,101,10)
```



In [52]:
np.random.randint(0,101,10)

array([74, 98, 46, 18, 26, 92, 52, 85, 68,  7])



```
np.random.seed(42)
np.random.rand(4)
```



In [54]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])



```
np.random.seed(101)
np.random.rand(4)
```



In [55]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])



```
np.random.seed(101)
np.random.rand(4)
```



In [56]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])



---





```
arr = np.arange(0,25)
```



In [62]:
arr = np.arange(0,25)



```
arr.reshape(5,5)
```



Cette ligne utilise la fonction `reshape()` pour modifier la forme d'un tableau existant.

`(5, 5)` : indique à reshape() quelle doit être la nouvelle forme du tableau. Dans ce cas, il spécifie que le tableau `arr` doit être remodelé en un tableau à deux dimensions avec 5 lignes et 5 colonnes (une matrice 5x5).

Imaginez que vous ayez une file de 25 personnes. `reshape(5, 5)` revient à dire à ces personnes de se réorganiser en une grille de 5x5. Le nombre total de personnes reste le même (25), mais elles sont organisées différemment.

*   Le nombre total d'éléments dans le tableau `(arr)` doit être compatible avec la nouvelle forme que vous demandez. Par exemple, si arr avait 25 éléments, le remodeler en (5, 5) fonctionnerait. Mais si `arr` avait 30 éléments, vous obtiendriez une erreur car vous ne pouvez pas faire tenir 30 éléments dans une grille de 5x5.
*   `reshape()` ne modifie pas les données d'origine dans le tableau ; il crée simplement une nouvelle vue du tableau avec une forme différente.

In [63]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])



```
arr.reshape(5,4)
```



La fonction `reshape()` est cruciale dans les architectures de réseaux de neurones pour les raisons suivantes :

### Formatage des données d'entrée
*   **Compatibilité avec les couches du réseau** : Les réseaux de neurones, en particulier les réseaux de neurones convolutifs (CNN) et les réseaux de neurones récurrents (RNN), ont des attentes spécifiques quant à la forme des données d'entrée. Par exemple, un CNN attendant des images en entrée aura besoin d'un tableau à 4 dimensions (nombre d'images, hauteur, largeur, canaux de couleur). `reshape()` permet de transformer les données brutes en une forme compatible avec l'architecture du réseau.
*   **Aplatissement des données** : Pour certaines couches, comme les couches entièrement connectées (dense layers), il est nécessaire d'aplatir les données en un vecteur unidimensionnel. `reshape()` permet de transformer des données multidimensionnelles en un vecteur unique, facilitant leur traitement par ces couches.
### Optimisation des performances
*   **Calcul vectoriel** : NumPy et les bibliothèques d'apprentissage automatique comme TensorFlow et PyTorch sont optimisées pour effectuer des opérations sur des tableaux multidimensionnels. `reshape()` permet d'organiser les données de manière à tirer parti de ces optimisations, accélérant ainsi les calculs.
Gestion de la mémoire: reshape() permet de manipuler la forme des données sans copier les données sous-jacentes, ce qui est plus efficace en termes de gestion de la mémoire, surtout lorsque l'on travaille avec de grands ensembles de données.
### Flexibilité et manipulation des données
*   **Transformation des données **: `reshape()` permet de transformer facilement la structure des données pour différentes tâches. Par exemple, on peut passer d'une représentation d'une image en niveaux de gris (2D) à une représentation en couleur (3D) en utilisant `reshape()`.
*   **Combinaison et division des données** : `reshape()` peut être utilisé pour combiner plusieurs tableaux en un seul ou pour diviser un grand tableau en plusieurs plus petits, offrant ainsi une grande flexibilité dans la manipulation des données.

In [64]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

ValueError: ignored



---





```
ranarr = np.random.randint(0,101,10)
```



In [68]:
ranarr = np.random.randint(0,101,10)



```
ranarr
```



In [69]:
ranarr

array([12, 93, 40, 49, 83,  8, 29, 59, 34, 44])



```
ranarr.max()
```



In [70]:
ranarr.max()

93



```
ranarr.min()
```



In [71]:
ranarr.min()

8



```
ranarr.argmax()
```



In [74]:
# Index du maximum
ranarr.argmax()

1



```
ranarr.argmin()
```



In [73]:
ranarr.argmin()

5



```
ranarr.dtype
```



In [75]:
ranarr.dtype

dtype('int64')



```
arr
```



In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])



```
arr.shape
```



In [78]:
arr.shape

(25,)



```
arr = arr.reshape(5,5)
```



In [79]:
arr = arr.reshape(5,5)



```
arr
```



In [80]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])



```
arr.shape
```



In [81]:
arr.shape

(5, 5)



```
arr.reshape(25,1)
```



In [82]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])



```
arr.reshape(1,25)
```



In [83]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

# Indexing and selection



```
arr = np.arange(0,11)
```



In [84]:
arr = np.arange(0,11)



```
arr
```



In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



```
arr[8]
```



In [86]:
arr[8]

8



```
arr[1:5]
```



In [88]:
arr[1:5]

array([1, 2, 3, 4])



```
arr[0:5]
```



In [89]:
arr[0:5]

array([0, 1, 2, 3, 4])



```
arr[:5]
```



In [90]:
arr[:5]

array([0, 1, 2, 3, 4])



```
arr[5:]
```



In [91]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])



```
arr
```



In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



```
arr[0:5] = 100
```



In [93]:
arr[0:5] = 100



```
arr
```



In [94]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])



```
arr = np.arange(0,11)
```



In [95]:
arr = np.arange(0,11)



```
slice_of_arr = arr[0:5]
```



In [96]:
slice_of_arr = arr[0:5]



```
slice_of_arr
```



In [97]:
slice_of_arr

array([0, 1, 2, 3, 4])



```
arr
```



In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



```
slice_of_arr[:] = 99
```



In [100]:
slice_of_arr[:] = 99



```
slice_of_arr
```



In [101]:
slice_of_arr

array([99, 99, 99, 99, 99])



```
arr
```



In [102]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])



```
arr_copy = arr.copy()
arr_copy[:] = 100
```



In [103]:
arr_copy = arr.copy()
arr_copy[:] = 100



```
arr_copy
```



In [104]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])



```
arr
```



In [105]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])



```
arr_2d = np.array(
    [[
        5,10,15
    ],[
        20,25,30
    ],[
        35,40,45
    ]]
)
```



In [106]:
arr_2d = np.array(
    [[5,10,15],
     [20,25,30],
     [35,40,45]]
)



```
arr_2d
```



In [107]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])



```
arr_2d.shape
```



In [108]:
arr_2d.shape

(3, 3)



```
arr_2d[2]
```



In [109]:
arr_2d[2]

array([35, 40, 45])



```
arr_2d[0,2]
```



In [110]:
arr_2d[0,2]

15



```
arr_2d[:2]
```



In [111]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])



```
arr_2d[:2,1:]
```



In [112]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])



```
arr = np.arange(1,11)
```



In [113]:
arr = np.arange(1,11)



```
arr
```



In [114]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



```
arr > 4
```



In [115]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])



```
bool_arr = arr>4
```



In [116]:
bool_arr = arr>4



```
bool_arr
```



In [117]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])



```
arr[bool_arr]
```



In [118]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])



```
arr[arr>4]
```



In [119]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Arithmetic Operations



```
arr = np.arange(0,10)
```



In [120]:
arr = np.arange(0,10)



```
arr
```



In [121]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



```
arr + 5
```



In [122]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])



```
arr - 2
```



In [123]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])



```
arr + arr
```



In [124]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])



```
arr * arr
```



In [125]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])



```
arr / arr
```



`arr / arr` : divise le tableau `arr` par lui-même, élément par élément.



*   **Division par zéro** : Si arr contient des zéros, vous rencontrerez un avertissement "division par zéro".
*   **Type de données** : Le tableau résultant aura le même type de données que `arr`. Si `arr` contient des entiers, le résultat peut également être des entiers, potentiellement avec des décimales tronquées en raison de la division entière. Si `arr` contient des nombres à virgule flottante, le résultat sera des nombres à virgule flottante.

In [126]:
arr / arr

<ipython-input-126-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])



```
1 / 0
```



In [127]:
1 / 0

ZeroDivisionError: division by zero

ZeroDivisionError: ignored



```
1 / arr
```



In [129]:
1 / arr

<ipython-input-129-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])



```
np.sqrt(arr)
```



In [130]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])



```
np.sin(arr)
```



In [131]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])



```
np.log(arr)
```



In [132]:
np.log(arr)

<ipython-input-132-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])



```
arr
```



In [133]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



```
arr.sum()
```



In [134]:
arr.sum()

45



```
arr.mean()
```



In [135]:
arr.mean()

4.5



```
arr.max()
```



In [136]:
arr.max()

9



```
arr.var()
```



In [137]:
arr.var()

8.25



```
arr.std()
```



In [138]:
arr.std()

2.8722813232690143



```
np.arange(0,25)
```



In [139]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])



```
np.arange(0,25).reshape(5,5)
```



In [140]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])



```
arr2d = np.arange(0,25).reshape(5,5)
```



In [141]:
arr2d = np.arange(0,25).reshape(5,5)



```
arr2d.shape
```



In [142]:
arr2d.shape

(5, 5)



```
arr2d
```



In [143]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])



```
arr2d.sum()
```



In [144]:
arr2d.sum()

300



```
arr2d.sum(axis=0)
```



In [145]:
# Somme par colonne
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])



```
arr2d.sum(axis=1)
```



In [146]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

# Exercices

Importez la bibliothèque NumPy et donnez-lui l'alias 'np' pour une utilisation simplifiée.

In [147]:
import numpy as np

Créez un tableau NumPy unidimensionnel contenant 10 éléments, tous initialisés à 0.

In [148]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Créez un tableau NumPy unidimensionnel contenant 10 éléments, tous initialisés à 1.

In [149]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Créez un tableau NumPy unidimensionnel contenant 10 éléments, tous initialisés à 1, puis multipliez chaque élément par 5.

In [150]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Créez un tableau NumPy unidimensionnel contenant tous les nombres entiers de 10 à 50 (inclus).

In [151]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Créez un tableau NumPy unidimensionnel contenant tous les nombres entiers pairs de 10 à 50 (inclus).

In [152]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Créez un tableau NumPy bidimensionnel de forme 3x3 contenant les nombres de 0 à 8, disposés en lignes successives.

In [194]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Créez une matrice identité 3x3.

In [157]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Générez un nombre aléatoire compris entre 0 (inclus) et 1 (exclu).

In [162]:
np.random.rand(1)

array([0.72965305])

array([0.0756819])

Générez un tableau NumPy unidimensionnel contenant 25 nombres aléatoires tirés d'une distribution normale standard.

In [160]:
np.random.randn(25)

array([ 0.56007451,  0.14005432,  1.39562331, -0.32091398,  1.27997523,
       -0.17043005,  0.3080472 , -1.06180767, -1.33171338,  2.08443716,
        1.75325834, -0.0604637 ,  0.7076698 , -1.0843546 ,  0.94127579,
        1.30117182, -0.15231533,  0.14377024,  0.39244774,  0.32178838,
        1.02904824, -0.27207863,  2.06079718, -1.04686723, -2.27373854])

array([ 0.91035914,  2.39810814,  1.43125938,  0.42334746,  0.06208316,
        0.2658639 , -0.09519518,  0.63311363, -0.21413838,  1.43666095,
       -0.28511481,  0.26328773,  1.51080327,  1.69877827, -0.39682137,
       -2.89835198,  0.76999556,  0.546213  ,  1.16893157,  0.98804578,
        0.98761444,  0.44744034,  1.08801834, -0.60188586, -0.27522432])

Créez un tableau NumPy unidimensionnel contenant tous les nombres entiers de 1 à 100 (inclus).

In [163]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Créez un tableau NumPy unidimensionnel contenant les nombres de 1 à 100 (inclus), divisez chaque nombre par 100, puis remodelez ce tableau en une matrice 10x10.

In [166]:
temp = np.arange(1,101) / 100
temp.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Créez un tableau NumPy unidimensionnel contenant 20 nombres uniformément espacés entre 0 et 1 (inclus).

In [167]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Créez une matrice 5x5 nommée mat contenant les nombres de 1 à 25 disposés en lignes successives, puis affichez cette matrice.

In [169]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Sélectionnez toutes les lignes de la matrice mat à partir de la 3ème ligne (index 2) jusqu'à la fin.

In [170]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Sélectionnez la partie de la matrice mat qui commence à la 3ème ligne (index 2) et à la 2ème colonne (index 1), et qui inclut toutes les lignes et colonnes suivantes:

```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [171]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Sélectionnez l'élément de la matrice mat situé à la 4ème ligne (index 3) et à la 5ème colonne (index 4).

In [172]:
mat[3,4]

20

20

Affichez le contenu de la matrice mat.

In [173]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Sélectionnez les 3 premières lignes de la matrice mat.

In [174]:
mat[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Sélectionnez les éléments situés dans les 3 premières lignes de la matrice mat et dans la 2ème colonne (index 1).

In [175]:
mat[:3,1]

array([ 2,  7, 12])

array([ 2,  7, 12])

Sélectionnez les éléments situés dans les 3 premières lignes de la matrice mat et dans la 2ème colonne (index 1), mais conservez la structure en 2 dimensions.

In [184]:
mat[:3,[1]]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

Sélectionnez tous les éléments de la dernière ligne de la matrice mat.

In [181]:
mat[-1:]

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

Sélectionnez les deux dernières lignes de la matrice mat.

In [182]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Calculez la somme de tous les éléments de la matrice mat.

In [187]:
mat.sum()

325

325

Calculez l'écart type de tous les éléments de la matrice mat.

In [191]:
mat.std()

7.211102550927978

7.211102550927978

Calculez la somme de chaque colonne de la matrice mat.

In [192]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

Initialisez le générateur de nombres aléatoires avec la graine (seed) 101, puis générez un nombre aléatoire compris entre 0 (inclus) et 1 (exclu).

Utiliser une graine permet de rendre les résultats du générateur de nombres aléatoires reproductibles. Si vous utilisez la même graine, vous obtiendrez la même séquence de nombres aléatoires à chaque exécution du code.

In [193]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])

array([0.51639863])